### ISSUE TITLE
Drop Java 7 support

### ISSUE THREAD

**Issue by jochenberger** [eddyson-de/tapestry-react#120]
Java 7 reached EOL more than 2 years ago, we should no longer consider compatibility a requirement.
If you use this library in a Java 7 environment and cannot upgrade, please let us know.
cc @felixgonschorek, @benweidig

**Comment by benweidig** [comment]
No problem for us, 100% Java 8 over here. Thx for the considerations.

**Comment by ydylla** [comment]
We are already on java 11 😄
