### ISSUE TITLE
0.35.0 artifacts not available in jitpack.io

### ISSUE THREAD

**Issue by felixgonschorek** [eddyson-de/tapestry-react#138]
Hi Jochen,

we are currently in the process of upgrading our projects to tapestry 5.8
We wantet to upgrade our dependency on tapestry-react to v0.35.0, but it seems the build in jitpack had a timeout - we can't download the dependency in our projects.

The build for 0.35.0 seems to have been successful, but in the end there is a timeout, we think that has been the deployment container that would have published the artifact.

Thank you if you find the time to look afters this issue!
Cheers
Felix

jitpack log of 0.35.0 build: https://jitpack.io/com/github/eddyson-de/tapestry-react/v0.35.0/build.log

**Comment by ydylla** [comment]
Sorry for the very late response.
The build for 0.35.0 (without the "v" prefix) was successful:  
https://jitpack.io/com/github/eddyson-de/tapestry-react/0.35.0/build.log
Using it as
```
implementation 'com.github.eddyson-de:tapestry-react:0.35.0'
```
should work.  
A build with tapestry 5.8 will also be available soon.
