### ISSUE TITLE
React addons are not available

### ISSUE THREAD

**Issue by jochenberger** [eddyson-de/tapestry-react#4]
The React addons are not available. I'd prefer having a separate `react/addons` module but that is not available (https://github.com/facebook/react/issues/5243). On the other hand, the reactcomponent module depends on the react module, so if we just add a react-with-addons module, we'll probably load all the things twice. We could add a symbol to toggle, whether to add the react.js or the react-with-components.js assets as "react" module. The current workaround would be to override the ModuleManager contribution.

**Comment by benweidig** [comment]
Also needing this I'm working on a pull request for this.

**Comment by jochenberger** [comment]
Until someone proposes a better solution, the preferred way to do this is now

``` java
@ApplicationDefaults
@Contribute(SymbolProvider.class)
public static void overrideReact(final MappedConfiguration<String, Object> configuration) {
  configuration.add(ReactSymbols.REACT_ASSET_PATH, "webjars:react:$version/react-with-addons.js");
}
```

**Comment by jochenberger** [comment]
From 0.17.1, there is a configuration symbol (`de.eddyson.tapestry.react.ReactSymbols.USE_REACT_WITH_ADDONS` or `tapestry.react.use_react_with_addons`) to toggle whether to use the build with or without addons. It defaults to `false`.
